sudo: required

language: generic

services:
  - docker

# Build & run tests
before_install:
  - docker build -t ebimodeling/ghgvcr .
  - docker run ebimodeling/ghgvcr /bin/sh -c "Rscript -e \"devtools::check()\""

# Only deploy on master
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
