# Use docker-compose for a local development environment.
version: "3"

# This volume will store & cache across containers the large data files
# necessary to run the server
volumes:
  data:
    driver: local
  lib:
    driver: local

services:
  ghgvcr:
    build:
      context: .
    volumes:
      - .:/app/
      - data:/app/data/
    stdin_open: true
    tty: true
    ports:
      - 6311:6311
    command: ["bin/download-files.sh", "&&", "bin/start-server.sh"]
